#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_JOYMONITOR                          107
#define IDC_JOYMONITOR                          109
#define IDD_JOY                                 111
#define IDB_GREENDOT                            118
#define IDB_GREYDOT                             120
#define IDB_REDDOT                              122
#define IDB_RING50                              125
#define IDI_INDICATOR                           127
#define IDS_APP_TITLE                           40000
#define IDS_POV1_2                              40000
#define IDC_POV_GRP                             40001
#define IDS_POV2_2                              40002
#define IDS_POV1_4                              40003
#define IDS_POV2_4                              40004
#define IDS_POV3_4                              40005
#define IDS_POV4_4                              40006
#define IDC_TXT_X                               40035
#define IDC_TXT_Y                               40036
#define IDC_TXT_Z                               40037
#define IDC_TXT_RX                              40038
#define IDC_TXT_RY                              40039
#define IDC_TXT_RZ                              40040
#define IDC_TXT_SL0                             40041
#define IDC_TXT_SL1                             40042
#define IDC_VJOY_AXES                           40050
#define IDC_VJOY_DEVICE                         40068
#define IDC_X                                   40100
#define IDC_Y                                   40101
#define IDC_Z                                   40102
#define IDC_RX                                  40103
#define IDC_RY                                  40104
#define IDC_RZ                                  40105
#define IDC_SL0                                 40106
#define IDC_SL1                                 40107
