#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_SMALL                               108
#define IDC_SPPCONSOLE                          109
#define IDD_SPPDIAG                             111
#define IDI_SPPCONSOLE                          114
#define IDD_LOGDLG                              117
#define IDC_CH_MONITOR                          1000
#define IDC_CHPP1                               1001
#define IDC_CHPP2                               1002
#define IDC_CHPP3                               1003
#define IDC_CHPP4                               1004
#define IDC_CHPP5                               1005
#define IDC_CHPP6                               1006
#define IDC_CHPP7                               1007
#define IDC_CHPP8                               1008
#define IDC_CH_INSIG                            1010
#define IDC_TXT_CHPP1                           1011
#define IDC_TXT_CHPP2                           1012
#define IDC_TXT_CHPP3                           1013
#define IDC_TXT_CHPP4                           1014
#define IDC_TXT_CHPP5                           1015
#define IDC_TXT_CHPP6                           1016
#define IDC_TXT_CHPP7                           1017
#define IDC_TXT_CHPP8                           1018
#define IDC_CH_PULSE                            1019
#define IDC_AUD_8                               1020
#define IDC_LIST_FILTERS                        1080
#define IDC_CH_LOG                              1081
#define IDS_APP_TITLE                           40000
#define IDS_F_STARTSPPPRS                       40001
#define IDS_I_STARTSPPPRS                       40002
#define IDS_W_FILTERDLL                         40003
#define IDS_I_FILTERDLL                         40004
#define IDS_E_FILTERDLLVER                      40005
#define IDS_E_FILTERDLLNF                       40006
#define IDS_I_FILTERDLLOK                       40007
#define IDS_W_FILTERSELFAIL                     40008
#define IDC_LIST_AUDIOSRC                       40009
#define IDS_E_FILTERSELFAIL                     40009
#define IDC_LIST_PCM                            40010
#define IDS_I_FILTERSELOK                       40010
#define IDS_W_VJOYMISSING                       40011
#define IDC_LIST_PPM                            40012
#define IDS_E_VJOYVERTOOOLD                     40012
#define IDC_CH1                                 40013
#define IDS_I_ENUM1                             40013
#define IDC_CH2                                 40014
#define IDS_E_STRSTRM1                          40014
#define IDC_CH3                                 40015
#define IDS_W_STRSTRM2                          40015
#define IDC_CH4                                 40016
#define IDS_E_STRSTRM3                          40016
#define IDC_CH5                                 40017
#define IDS_E_STRSTRM4                          40017
#define IDC_CH6                                 40018
#define IDS_E_STRSTRM5                          40018
#define IDC_CH7                                 40019
#define IDS_E_INITEP1                           40019
#define IDC_CH8                                 40020
#define IDS_I_INITPLSOBJ5                       40020
#define IDS_I_CHANGE_DEFDEV                     40021
#define IDS_W_CHANGE_DEFDEV                     40022
#define IDS_CHANGE_ENDEV                        40023
#define IDS_W_ISCAP_IDNOTFOUND                  40024
#define IDS_E_ISCAP_EPNOTFOUND                  40025
#define IDS_W_ISEXT_IDNOTFOUND                  40026
#define IDS_W_ISEXT_TOPO                        40027
#define IDS_W_ISEXT_NOCONN                      40028
#define IDS_W_ISEXT_NOTYPE                      40029
#define IDC_TXT_CH1                             40030
#define IDS_W_DEVPEAK_IDNOTFOUND                40030
#define IDC_TXT_CH2                             40031
#define IDS_W_DEVPEAK_ACTCLNT                   40031
#define IDC_TXT_CH3                             40032
#define IDS_W_DEVPEAK_MXFRMT                    40032
#define IDC_TXT_CH4                             40033
#define IDS_I_ADDDEV_START                      40033
#define IDC_TXT_CH5                             40034
#define IDS_W_ADDDEV_IDNOTFOUND                 40034
#define IDC_TXT_CH6                             40035
#define IDS_W_ADDDEV_STATE                      40035
#define IDC_TXT_CH7                             40036
#define IDS_W_ADDDEV_PROP                       40036
#define IDC_TXT_CH8                             40037
#define IDS_W_ADDDEV_FRND                       40037
#define IDC_EDIT_LOG                            40038
#define IDS_E_REGNOT_FAIL                       40038
#define IDS_W_CHPEAK_IDNOTFOUND                 40039
#define IDS_W_CHPEAK_ACTCLNT                    40040
#define IDS_W_CHPEAK_MXFRMT                     40041
#define IDS_W_CHPEAK_NOINIT                     40042
#define IDS_W_CHPEAK_ACTMTR                     40043
#define IDS_W_CHPEAK_MTRCNT                     40044
#define IDS_W_CHPEAK_GETVAL                     40045
#define IDS_W_DEVPEAK_NOINIT                    40046
#define IDS_W_DEVPEAK_ACTMTR                    40047
#define IDS_W_DEVPEAK_MTRCNT                    40048
#define IDS_W_DEVPEAK_GETVAL                    40049
#define IDS_W_START_STOP                        40050
#define IDS_W_START_SET                         40051
#define IDS_W_START_INITEP                      40052
#define IDS_W_START_STREAM                      40053
#define IDS_E_INITEP_NOID                       40054
#define IDS_W_INITEP_IDNOTFOUND                 40055
#define IDS_W_INITEP_ACTCLNT                    40056
#define IDS_W_INITEP_MXFRMT                     40057
#define IDS_W_INITEP_FRMT                       40058
#define IDS_E_INITEP_FRMTSUP                    40059
#define IDS_E_INITEP_EVTHND                     40060
#define IDS_E_INITEP_NOCAPT                     40061
#define IDS_W_INITEP_NOINIT                     40062
#define IDS_W_STPSTR_NOSTOP                     40063
#define IDS_W_STRTSTR_NOSTART                   40064
#define IDS_E_PROCPACK_GETBUF                   40065
#define IDS_W_PROCPACK_DISC                     40066
#define IDS_E_PROCPACK_PRW                      40067
#define IDS_E_PROCPACK_RLS                      40068
#define IDS_E_PROCPACK_PADD                     40069
#define IDS_I_INITPULSE                         40070
#define IDS_E_INITPULSE                         40071
#define IDC_TXT_CHPP9                           40072
#define IDS_I_RESTAUDIO                         40072
#define IDS_E_RESTAUDIO_NOAUDIO                 40073
#define IDC_TXT_CHPP10                          40074
#define IDS_E_RESTAUDIO_NOSPP                   40074
#define IDS_E_RESTAUDIO_SSFAIL                  40075
#define IDC_TXT_CHPP11                          40076
#define IDS_E_RESTAUDIO_NOID                    40076
#define IDS_I_RESTAUDIO_OK                      40077
#define IDC_TXT_CHPP12                          40078
#define IDS_E_RESTAUDIO_FAIL                    40078
#define IDS_E_STREAMFAIL                        40079
#define IDC_TXT_CHPP13                          40080
#define IDS_E_STREAMTHRDFAIL                    40080
#define IDS_I_STREAMTHRDOK                      40081
#define IDC_TXT_CHPP14                          40082
#define IDS_I_AUDIOCHANGE                       40082
#define IDS_I_STARTSTREAM                       40083
#define IDC_TXT_CHPP15                          40084
#define IDS_I_CAPTURESTART                      40084
#define IDS_I_CAPTUREABORT                      40085
#define IDC_TXT_CHPP16                          40086
#define IDC_X                                   40087
#define IDC_Y                                   40088
#define IDC_Z                                   40089
#define IDC_RX                                  40090
#define IDC_RY                                  40091
#define IDC_RZ                                  40092
#define IDC_SL0                                 40093
#define IDC_SL1                                 40094
#define IDC_STATIC_X                            40095
#define IDC_STATIC_Y                            40096
#define IDC_STATIC_Z                            40099
#define IDC_STATIC_RX                           40100
#define IDC_STATIC_RY                           40105
#define IDC_STATIC_RZ                           40106
#define IDC_STATIC_SL0                          40107
#define IDC_STATIC_SL1                          40108
#define IDC_SRC_X                               40109
#define IDC_SRC_Y                               40110
#define IDC_SRC_Z                               40111
#define IDC_SRC_RX                              40112
#define IDC_SRC_RY                              40113
#define IDC_SRC_RZ                              40114
#define IDC_SRC_SL0                             40115
#define IDC_SRC_SL1                             40116
#define IDC_BTN_MAP                             40124
#define IDC_AUD_16                              40126
#define IDC_LEFT                                40128
#define IDC_MONO                                40130
#define IDC_RIGHT                               40132
#define IDC_VJOY_DEVICE                         40134
