#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_SMALL                               108
#define IDC_SPPCONSOLE                          109
#define IDD_SPPDIAG                             111
#define IDI_SPPCONSOLE                          114
#define IDD_LOGDLG                              117
#define IDC_CH_MONITOR                          1001
#define IDC_LIST_FILTERS                        1002
#define IDS_APP_TITLE                           40000
#define IDS_F_STARTSPPPRS                       40001
#define IDS_I_STARTSPPPRS                       40002
#define IDS_W_FILTERDLL                         40003
#define IDS_I_FILTERDLL                         40004
#define IDS_E_FILTERDLLVER                      40005
#define IDS_E_FILTERDLLNF                       40006
#define IDS_I_FILTERDLLOK                       40007
#define IDS_W_FILTERSELFAIL                     40008
#define IDC_LIST_AUDIOSRC                       40009
#define IDS_E_FILTERSELFAIL                     40009
#define IDC_LIST_PCM                            40010
#define IDS_I_FILTERSELOK                       40010
#define IDS_W_VJOYMISSING                       40011
#define IDC_LIST_PPM                            40012
#define IDS_E_VJOYVERTOOOLD                     40012
#define IDC_CH1                                 40013
#define IDS_I_ENUM1                             40013
#define IDC_CH2                                 40014
#define IDS_E_STRSTRM1                          40014
#define IDC_CH3                                 40015
#define IDS_W_STRSTRM2                          40015
#define IDC_CH4                                 40016
#define IDS_E_STRSTRM3                          40016
#define IDC_CH5                                 40017
#define IDS_E_STRSTRM4                          40017
#define IDC_CH6                                 40018
#define IDS_E_STRSTRM5                          40018
#define IDC_CH7                                 40019
#define IDS_E_INITEP1                           40019
#define IDC_CH8                                 40020
#define IDS_I_INITPLSOBJ5                       40020
#define IDS_I_CHANGE_DEFDEV                     40021
#define IDS_W_CHANGE_DEFDEV                     40022
#define IDS_CHANGE_ENDEV                        40023
#define IDS_W_ISCAP_IDNOTFOUND                  40024
#define IDS_E_ISCAP_EPNOTFOUND                  40025
#define IDS_W_ISEXT_IDNOTFOUND                  40026
#define IDS_W_ISEXT_TOPO                        40027
#define IDS_W_ISEXT_NOCONN                      40028
#define IDS_W_ISEXT_NOTYPE                      40029
#define IDC_TXT_CH1                             40030
#define IDS_W_DEVPEAK_IDNOTFOUND                40030
#define IDC_TXT_CH2                             40031
#define IDS_W_DEVPEAK_ACTCLNT                   40031
#define IDC_TXT_CH3                             40032
#define IDS_W_DEVPEAK_MXFRMT                    40032
#define IDC_TXT_CH4                             40033
#define IDS_I_ADDDEV_START                      40033
#define IDC_TXT_CH5                             40034
#define IDC_TXT_CH6                             40035
#define IDC_TXT_CH7                             40036
#define IDC_TXT_CH8                             40037
#define IDC_EDIT_LOG                            40038
