#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_SMALL                               108
#define IDC_SPPCONSOLE                          109
#define IDD_SPPDIAG                             111
#define IDI_SPPCONSOLE                          114
#define IDD_LOGDLG                              117
#define IDC_CH_MONITOR                          1001
#define IDC_LIST_FILTERS                        1002
#define IDS_APP_TITLE                           40000
#define IDS_F_STARTSPPPRS                       40001
#define IDS_I_STARTSPPPRS                       40002
#define IDS_W_FILTERDLL                         40003
#define IDS_I_FILTERDLL                         40004
#define IDS_E_FILTERDLLVER                      40005
#define IDS_E_FILTERDLLNF                       40006
#define IDS_I_FILTERDLLOK                       40007
#define IDS_W_FILTERSELFAIL                     40008
#define IDC_LIST_AUDIOSRC                       40009
#define IDS_E_FILTERSELFAIL                     40009
#define IDC_LIST_PCM                            40010
#define IDS_I_FILTERSELOK                       40010
#define IDS_W_VJOYMISSING                       40011
#define IDC_LIST_PPM                            40012
#define IDS_E_VJOYVERTOOOLD                     40012
#define IDC_CH1                                 40013
#define IDC_CH2                                 40014
#define IDC_CH3                                 40015
#define IDC_CH4                                 40016
#define IDC_CH5                                 40017
#define IDC_CH6                                 40018
#define IDC_CH7                                 40019
#define IDC_CH8                                 40020
#define IDC_TXT_CH1                             40030
#define IDC_TXT_CH2                             40031
#define IDC_TXT_CH3                             40032
#define IDC_TXT_CH4                             40033
#define IDC_TXT_CH5                             40034
#define IDC_TXT_CH6                             40035
#define IDC_TXT_CH7                             40036
#define IDC_TXT_CH8                             40037
#define IDC_EDIT_LOG                            40038
